name: SpellCheck
on: [pull_request]
jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install codespell flake8
      - run: |
          SKIP="./.*, ./zip_password_cracker/passwords.txt"
          codespell --ignore-words-list=ans,fo,followings,hist,iff,secant,som,tim --skip=$SKIP --quiet-level=2
      - name: Codespell comment
        if: ${{ failure() }}
        uses: plettich/python_codespell_action@master